// Spec: specs/013-foto-producto-web-ios/spec.md
// (originally Spec: specs/010-logo-heic-iphone/spec.md)
//
// Image normalization — IO (mobile / non-web) implementation. Shared by
// the store logo (F010) and the product photo (F013) upload paths.
//
// On mobile the image_picker already honours `maxWidth` / `imageQuality`,
// but routing every platform through the same normalizer guarantees a
// PNG output and a downsized image regardless of what the picker returns
// (some Android galleries hand back the original file untouched).
//
// Spec 010 §9 / D1: the output is **PNG**, not JPEG. Tenderos often hand
// over a logo generated by an AI (ChatGPT, Nano Banana/Gemini); those
// generators emit PNG/WebP, frequently with a transparent background.
// `package:image`'s `decodeImage` keeps the alpha channel of PNG/WebP
// inputs and `encodePng` writes it back out, so a transparent logo stays
// transparent instead of being flattened to a black box (which is what a
// JPEG re-encode did).
//
// Decoding here uses `package:image` (pure Dart). The web path instead
// decodes with the browser — see `image_normalizer_web.dart`.

import 'dart:typed_data';

import 'package:image/image.dart' as img;
import 'package:image_picker/image_picker.dart';

import 'image_normalizer_types.dart';

const _cannotProcessMessage = 'No pudimos procesar esa foto. Intente con '
    'otra, o tome una captura de pantalla de la foto y súbala.';

/// IO implementation of `normalizeImageForUpload`. Selected by the
/// conditional import in `image_normalizer.dart` on every non-web
/// platform.
///
/// `package:image`'s `decodeImage` auto-detects the format from the bytes,
/// so PNG, JPEG and WebP (the usual AI-generator outputs) all decode here
/// without any per-format branching.
Future<Uint8List> normalizeImageForUploadImpl(XFile source) async {
  final bytes = await source.readAsBytes();

  final decoded = img.decodeImage(bytes);
  if (decoded == null) {
    // `package:image` could not recognize the bytes as any image format.
    throw const ImageNormalizationException(_cannotProcessMessage);
  }

  // Encode as PNG. `encodePng` keeps whatever alpha channel the decoded
  // image has, so a transparent AI logo round-trips with its transparency
  // intact. Start at the standard cap and shrink further only if a
  // pathological input pushes the PNG over the backend's 2MB limit.
  var maxSide = kLogoMaxSide;
  while (true) {
    final resized = _resizeToFit(decoded, maxSide);
    final png = img.encodePng(resized);
    if (png.length <= kLogoMaxBytes || maxSide <= kLogoMinSide) {
      if (png.length > kLogoMaxBytes) {
        // Even at the minimum side the PNG is too heavy — refuse rather
        // than upload an image the backend would reject with a 2MB error.
        throw const ImageNormalizationException(
          'Esa imagen es demasiado pesada. Intente con una foto más '
          'sencilla o con menos detalle.',
        );
      }
      return png;
    }
    // Halve the longest-side budget and retry; clamp to the floor so the
    // loop always terminates at `kLogoMinSide`.
    maxSide = (maxSide ~/ 2).clamp(kLogoMinSide, kLogoMaxSide);
  }
}

/// Returns [image] resized so its longest side is at most [maxSide].
/// Smaller images are returned unchanged — never upscaled.
img.Image _resizeToFit(img.Image image, int maxSide) {
  final longestSide =
      image.width >= image.height ? image.width : image.height;
  if (longestSide <= maxSide) {
    return image;
  }
  // Constrain the longest side and let `package:image` keep the aspect
  // ratio for the other dimension. `copyResize` preserves the alpha
  // channel of the source image.
  if (image.width >= image.height) {
    return img.copyResize(image, width: maxSide);
  }
  return img.copyResize(image, height: maxSide);
}
