// Spec: specs/010-logo-heic-iphone/spec.md
//
// Logo image normalization — public, cross-platform facade.
//
// Why this exists: iPhone photos are HEIC. On Flutter web `image_picker`
// ignores `maxWidth` / `imageQuality`, so a raw HEIC reached the backend
// untouched; the Supabase `store-logos` bucket only accepts
// jpeg/png/webp/gif and rejected `image/heic` -> 500 "error al subir logo".
//
// The fix: re-encode every logo to a downsized **PNG** BEFORE upload.
//   - Web   -> decode with the BROWSER (a `<canvas>`), which on Safari can
//              decode HEIC, then export `image/png`. See
//              `image_normalizer_web.dart`.
//   - Mobile / other -> decode with `package:image`. See
//              `image_normalizer_io.dart`.
//
// Spec 010 §9 / D1 (refined 2026-05-18): the output is PNG, not JPEG.
// Tenderos commonly upload a logo generated by an AI (ChatGPT, Nano
// Banana/Gemini); those generators emit PNG/WebP with a TRANSPARENT
// background. A JPEG re-encode flattens that transparency onto black —
// the logo arrives as a black box. PNG keeps the alpha channel, so the
// transparent background survives. The longest side is capped at ~768px
// to keep even an opaque PNG under the backend's 2MB limit.
//
// The conditional import picks the right implementation at compile time.
// Shared types (`ImageNormalizationException`, the size/byte constants)
// live in `image_normalizer_types.dart` so both implementations and this
// facade can reference them without an import cycle.

import 'dart:typed_data';

import 'package:image_picker/image_picker.dart';

import 'image_normalizer_io.dart'
    if (dart.library.html) 'image_normalizer_web.dart';
import 'image_normalizer_types.dart';

export 'image_normalizer_types.dart'
    show
        ImageNormalizationException,
        kLogoMaxSide,
        kLogoMaxBytes,
        kLogoMinSide;

/// Re-encodes [source] into a downsized **PNG** suitable for upload to the
/// `store-logos` bucket.
///
/// - The longest side is capped at [kLogoMaxSide]; smaller images are not
///   upscaled.
/// - Output is always PNG. The alpha channel of a transparent source
///   (PNG/WebP from an AI logo generator) is preserved — it is never
///   flattened to an opaque background.
/// - The PNG stays under [kLogoMaxBytes]; a pathological input is shrunk
///   further until it fits.
///
/// Throws [ImageNormalizationException] (with a Spanish message) when the
/// image cannot be decoded or cannot be brought under the size cap.
Future<Uint8List> normalizeLogoImage(XFile source) =>
    normalizeLogoImageImpl(source);
