// Spec: specs/010-logo-heic-iphone/spec.md
//
// Shared types & constants for logo image normalization. Kept in a
// dependency-free file so both the IO and web implementations and the
// public facade can import it without forming an import cycle.

/// Maximum length (in pixels) of the longest side of a normalized logo.
///
/// Spec 010 §9 / D1 (refined 2026-05-18): the normalizer outputs **PNG**
/// (not JPEG) so a logo generated by an AI (ChatGPT, Nano Banana/Gemini)
/// keeps its transparent background instead of turning into a black box.
/// A PNG is heavier than a JPEG of the same dimensions, so the longest
/// side is capped at ~768px — small enough that even a photographic,
/// fully-opaque 768px PNG stays well under the backend's 2MB limit, while
/// still being sharp for a logo shown at a few hundred px.
const int kLogoMaxSide = 768;

/// Hard ceiling (in bytes) the normalized logo must stay under. Mirrors the
/// backend's 2MB cap on logo uploads. If a pathological input (e.g. a noisy
/// fully-opaque photo saved as PNG) exceeds this, the normalizer shrinks the
/// image further until it fits — see the IO/web implementations.
const int kLogoMaxBytes = 2 * 1024 * 1024;

/// Smallest longest-side the size-reduction fallback will shrink to before
/// giving up. A logo below this is unusably small; if a PNG still exceeds
/// [kLogoMaxBytes] at this size the normalizer throws instead of uploading
/// an image the backend would reject.
const int kLogoMinSide = 256;

/// Thrown when a picked image cannot be decoded / re-encoded — e.g. the
/// bytes are corrupt, the browser cannot decode the source format (a
/// non-Safari browser handed a HEIC file), or the re-encoded PNG cannot be
/// brought under [kLogoMaxBytes].
///
/// The [message] is in Spanish so callers can surface it directly to the
/// merchant (Constitution Art. V). Never swallow this exception silently.
class ImageNormalizationException implements Exception {
  const ImageNormalizationException(this.message);

  /// User-facing Spanish message describing what happened and what to do.
  final String message;

  @override
  String toString() => 'ImageNormalizationException: $message';
}
