// Spec: specs/013-foto-producto-web-ios/spec.md
// (originally Spec: specs/010-logo-heic-iphone/spec.md)
//
// Tests for the `normalizeImageForUpload` IO path (mobile / non-web),
// which re-encodes a picked image (a store logo or a product photo) to a
// downsized PNG with `package:image`. F013 generalized the F010
// normalizer name from `normalizeLogoImage` so the product-photo upload
// path can reuse it.
//
// Why this matters: iPhone photos are HEIC and tenderos also upload logos
// generated by an AI (ChatGPT, Nano Banana/Gemini) that come as PNG/WebP
// with a TRANSPARENT background. On Flutter web `image_picker` ignores
// `maxWidth` / `imageQuality`, so the raw image reached the backend
// untouched. Spec 010 §9 / D1 normalizes every logo to **PNG** (max side
// ~768px) BEFORE upload — PNG so a transparent AI logo keeps its alpha
// instead of being flattened to a black box (a JPEG re-encode did exactly
// that). These tests exercise the IO decoder/resizer; the web path decodes
// via the browser (`<canvas>`), which cannot be unit-tested in the Dart VM.

import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart' as img;
import 'package:image_picker/image_picker.dart';
import 'package:vendia_pos/services/image_normalizer.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  /// Builds a synthetic [XFile] backed by an encoded image of the given
  /// size, so the test runs entirely in memory (no filesystem, no network).
  ///
  /// [format] picks the encoded container: `png` or `jpg`. (WebP cannot be
  /// synthesized — `package:image` 4.x has a WebP decoder but no encoder —
  /// so the WebP case uses the real fixture below.)
  /// When [transparent] is true the image carries an alpha channel and the
  /// left half of every row is fully transparent, so a later check can
  /// prove the normalizer did not flatten the transparency away.
  XFile syntheticImage({
    required int width,
    required int height,
    required String name,
    required String mimeType,
    String format = 'jpg',
    bool transparent = false,
  }) {
    final image = img.Image(
      width: width,
      height: height,
      numChannels: transparent ? 4 : 3,
    );
    // Fill with a non-uniform gradient so resizing produces real output.
    for (var y = 0; y < height; y++) {
      for (var x = 0; x < width; x++) {
        if (transparent && x < width ~/ 2) {
          // Left half: fully transparent pixels (alpha 0).
          image.setPixelRgba(x, y, 0, 0, 0, 0);
        } else if (transparent) {
          // Right half: fully opaque coloured pixels (alpha 255).
          image.setPixelRgba(x, y, x % 256, y % 256, (x + y) % 256, 255);
        } else {
          image.setPixelRgb(x, y, x % 256, y % 256, (x + y) % 256);
        }
      }
    }
    final bytes = format == 'png'
        ? img.encodePng(image)
        : img.encodeJpg(image, quality: 95);
    return XFile.fromData(bytes, name: name, mimeType: mimeType);
  }

  /// A real 200x150 lossless **WebP** with an alpha channel: the left half
  /// is fully transparent, the right half is an opaque gradient. WebP is a
  /// typical AI-logo-generator output and `package:image` 4.x has no WebP
  /// encoder, so this fixture is embedded as base64 rather than synthesized.
  XFile webpFixture() {
    const base64Webp =
        'UklGRloDAABXRUJQVlA4TE0DAAAvx0AlEM2ISRP817+zDSL6HxW8haK2kRzzR7wE'
        'dq+Xp+K2kdTUPJfpcMD7PwGgbLelDFCUWlDQ3b9A0J9moewKcNxG4mz//9Hsjt2'
        'ByLo+TM3GC09Ek7MRDNq2EeT70Xn+5JZJCtq2kZyxG3869wgIivwfbQIKaWH59z'
        'I8aZl89b6sib/AQ5aGMp/GPwblRnlEQdmhfASBEm4QKMeKgrIYQSDdIHBWm+4Dm'
        'UaLymU9EOm2x3fjgTirPaT7QKbRHs56INJtj2k8EGe1h3QfyDTaw1kPRLrtMY0H'
        '4qz2kO4DmS3irAdq5GumEQTSDQJnRcE0gkC6QeCs/iryJtPoreJAvoMSbl/VG0V'
        'e46zuqjfyFdPosHojP0QJt8vqjSIf4KxeqzfyK6bRb/VGVpRwe67eKAJndV69k'
        'abRffVGKW4A6u2sDAHmHmQEKOFuFOk/zsJG9p5pqDey6yjh+vJGkY7jrC/VG9l'
        'tpvG1eiP7jBLuR+qNIj3GWS/UG9lfpvFSvZGdRQn3DfVGka7irPfUG9lRpvGuev'
        'cUJdz3tfMhOCsKphEE0g0CZ0XBNIJAukHgrCiYRhBIt0njgTirRX+6D2Qa7eGs'
        'ByLd9pjGA3FWe0j3gUyjPZz1QKTbHtN4IM5qD+k+kGm0h7MeiGyRaTxQI18i3S'
        'BwVhRMIwikGwTOioJpBIF0g8BZUTCNIJBuEDgrCqYRBNINAmdFwTSCQLpB4Kwo'
        'mEYQSDcInBUF0wgC6QaBs6JgGkEg3SBwVhRMIwikGwTOioJpBIF0g8BZnwMA';
    final bytes = base64Decode(base64Webp);
    return XFile.fromData(bytes, name: 'logo-ia.webp', mimeType: 'image/webp');
  }

  group('normalizeImageForUpload — IO path (mobile re-encode)', () {
    test('output is always PNG and decodable', () async {
      final source = syntheticImage(
        width: 1500,
        height: 900,
        name: 'banner.jpg',
        mimeType: 'image/jpeg',
        format: 'jpg',
      );

      final result = await normalizeImageForUpload(source);

      expect(result, isNotEmpty);
      // `findFormatForData` reports the encoded format of the bytes.
      expect(img.findFormatForData(result), img.ImageFormat.png,
          reason: 'output must be PNG regardless of the input format');
      expect(img.decodeImage(result), isNotNull,
          reason: 'output must be a valid, decodable image');
    });

    test('a large JPEG is re-encoded as PNG with the longest side <= 768px',
        () async {
      final source = syntheticImage(
        width: 3000,
        height: 2000,
        name: 'foto.jpg',
        mimeType: 'image/jpeg',
        format: 'jpg',
      );

      final result = await normalizeImageForUpload(source);

      expect(img.findFormatForData(result), img.ImageFormat.png);
      final decoded = img.decodeImage(result);
      expect(decoded, isNotNull);
      expect(decoded!.width, lessThanOrEqualTo(768));
      expect(decoded.height, lessThanOrEqualTo(768));
      // The longest side should be exactly the 768 cap (aspect kept).
      expect(decoded.width, 768);
    });

    test('a large PNG is downsized so the longest side is <= 768px',
        () async {
      final source = syntheticImage(
        width: 2400,
        height: 2400,
        name: 'logo.png',
        mimeType: 'image/png',
        format: 'png',
      );

      final result = await normalizeImageForUpload(source);

      expect(img.findFormatForData(result), img.ImageFormat.png);
      final decoded = img.decodeImage(result);
      expect(decoded, isNotNull);
      expect(decoded!.width, 768);
      expect(decoded.height, 768);
    });

    test('a transparent PNG keeps its alpha — not flattened to black',
        () async {
      // An AI-generated logo: a 1200px PNG whose left half is fully
      // transparent. The normalizer must NOT composite it onto black.
      final source = syntheticImage(
        width: 1200,
        height: 1200,
        name: 'logo-ia.png',
        mimeType: 'image/png',
        format: 'png',
        transparent: true,
      );

      final result = await normalizeImageForUpload(source);

      expect(img.findFormatForData(result), img.ImageFormat.png);
      final decoded = img.decodeImage(result);
      expect(decoded, isNotNull);
      // The decoded PNG must still carry an alpha channel.
      expect(decoded!.hasAlpha, isTrue,
          reason: 'a transparent logo must keep its alpha channel');
      // A pixel from the (downsized) transparent left region must still be
      // transparent — proof the background was not flattened to black.
      final topLeft = decoded.getPixel(0, 0);
      expect(topLeft.a, 0,
          reason: 'the transparent background must survive normalization');
    });

    test('a transparent WebP decodes and is re-encoded as PNG with alpha',
        () async {
      // A WebP is a typical AI-logo-generator output. The normalizer must
      // decode it and keep its transparent background in the PNG output.
      final source = webpFixture();

      final result = await normalizeImageForUpload(source);

      expect(img.findFormatForData(result), img.ImageFormat.png,
          reason: 'a WebP input must be re-encoded as PNG');
      final decoded = img.decodeImage(result);
      expect(decoded, isNotNull,
          reason: 'the WebP fixture must decode successfully');
      // 200x150 is under the 768 cap, so dimensions are kept.
      expect(decoded!.width, 200);
      expect(decoded.height, 150);
      expect(decoded.hasAlpha, isTrue);
      expect(decoded.getPixel(0, 0).a, 0,
          reason: 'the WebP transparent background must survive');
    });

    test('a transparent PNG that is small keeps its size and transparency',
        () async {
      final source = syntheticImage(
        width: 400,
        height: 300,
        name: 'logo-pequeno.png',
        mimeType: 'image/png',
        format: 'png',
        transparent: true,
      );

      final result = await normalizeImageForUpload(source);

      final decoded = img.decodeImage(result);
      expect(decoded, isNotNull);
      // No upscaling — original dimensions are kept.
      expect(decoded!.width, 400);
      expect(decoded.height, 300);
      expect(decoded.hasAlpha, isTrue);
      expect(decoded.getPixel(0, 0).a, 0);
    });

    test('a small image keeps its size (no upscaling)', () async {
      final source = syntheticImage(
        width: 300,
        height: 200,
        name: 'pequeno.jpg',
        mimeType: 'image/jpeg',
        format: 'jpg',
      );

      final result = await normalizeImageForUpload(source);

      final decoded = img.decodeImage(result);
      expect(decoded, isNotNull);
      expect(decoded!.width, 300);
      expect(decoded.height, 200);
    });

    test('the normalized PNG stays under the 2MB backend limit', () async {
      // A large, noisy gradient is the worst realistic case for PNG size.
      final source = syntheticImage(
        width: 4000,
        height: 4000,
        name: 'foto-grande.jpg',
        mimeType: 'image/jpeg',
        format: 'jpg',
      );

      final result = await normalizeImageForUpload(source);

      expect(result.length, lessThanOrEqualTo(2 * 1024 * 1024),
          reason: 'a 768px PNG must stay under the backend 2MB cap');
    });

    test('throws a clear exception when the bytes are not a valid image',
        () async {
      final garbage = XFile.fromData(
        // Random bytes that are not any known image format.
        Uint8List.fromList(List<int>.generate(128, (i) => (i * 7) % 256)),
        name: 'roto.bin',
        mimeType: 'application/octet-stream',
      );

      expect(
        () => normalizeImageForUpload(garbage),
        throwsA(isA<ImageNormalizationException>()),
      );
    });
  });
}
